name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        filter: blob:none
    - run: sudo apt install -y libalpm
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - uses: hynek/setup-cached-uv@v2
      with:
        cache-dependency-path: pyproject.toml
    - run: uv pip install --system -e .[test] pytest-md
    - uses: pavelzw/pytest-action@v2
      with:
        custom-arguments: --color=yes
        click-to-expand: false
        verbose: true
        job-summary: true
        emoji: false
