name: Check updated package

on:
  pull_request:
    paths:
    - 'pkgs/**'

jobs:
  linux:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    if: ${{ !github.event.pull_request.draft }}
    steps:
    - run: pacman -Sy --noconfirm git
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        filter: blob:none
    - run: ls
    - uses: tj-actions/changed-files@v45
      id: changed-files
      with:
        dir_names: true
        dir_names_include_files: pkgs/*
        files: pkgs/**
    - uses: flying-sheep/check@v1
      with:
        success: ${{ fromJson(steps.changed-files.outputs.all_changed_files_count) == 1 }}
    - uses: edlanglois/pkgbuild-action@v1
      id: makepkg
      with:
        pkgdir: ${{ steps.changed-files.outputs.all_changed_files }}
        aurDeps: true
    - uses: actions/upload-artifact@v4
      with:
        path: ${{ steps.makepkg.outputs.pkgfile0 }}
