name: Check updated package

on:
  pull_request:
    paths:
    - 'pkgs/**'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        filter: blob:none
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v45
      with:
        dir_names: true
        dir_names_include_files: pkgs/*
        files: pkgs/**
    - name: List all changed files
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        for file in ${ALL_CHANGED_FILES}; do
          echo "$file was changed"
        done
    #- name: Build Arch Linux package
    #  uses: FFY00/build-arch-package@v1
    #  with:
    #      PKGBUILD: path/to/my/PKGBUILD
